pipeline{
    agent any
    tools{
        maven 'Maven386'
    }
    stages{
        stage('Build Maven Project'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/snazeergit/DevOpsIntegration']]])
                 sh "mvn -f C:/ProgramData/Jenkins/.jenkins/workspace/DevOps-Automation-1/SpringRestProj01-SendingJSONData/pom.xml clean install"
            }
        }
        stage('Build Docker Image'){
            steps{
                script{
                 sh "docker build -t nazeerdocker/devops-automation-1 C:/ProgramData/Jenkins/.jenkins/workspace/DevOps-Automation-1/SpringRestProj01-SendingJSONData"
                }
            }
        }
        stage('Push Docker Image to DockerHub'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                        shell 'docker login -u nazeerdocker -p${dockerhubpwd}'
                    }
                    sh 'docker push nazeerdocker/devops-automation-1'
                }
            }
        }
    }
}